export {default as Home} from '../assets/home.png'
export {default as Ads} from '../assets/ads.png'
export {default as Chat} from '../assets/chat.png'
export {default as Group} from '../assets/group.png'
export {default as Marketplace} from '../assets/marketplace.png'
export {default as Page} from '../assets/page.png'
export {default as Post} from '../assets/post.png'
export {default as Profile} from '../assets/profile.png'
export {default as Setting} from '../assets/setting.png'

export {default as Online1} from '../assets/online1.png'
export {default as Online2} from '../assets/online2.png'
export {default as Online3} from '../assets/online3.png'
export {default as Online4} from '../assets/online4.png'
export {default as Online5} from '../assets/online5.png'
export {default as Online6} from '../assets/online6.png'
export {default as Online7} from '../assets/online7.png'

export {default as LoginPhone} from '../assets/loginphone.png'
export {default as Login1} from '../assets/login1.png'
export {default as Login2} from '../assets/login2.png'
export {default as Login3} from '../assets/login3.png'
export {default as Logo} from '../assets/logo.png'

export {default as GoogleIcon} from '../assets/google-icon.svg'
export {default as BgSignup} from '../assets/bg-signup.png'
export {default as AppleIcon} from '../assets/apple-icon.svg'


export {default as ShareIcon} from '../assets/share.png'
export {default as CommentIcon} from '../assets/comment.png'
export {default as HeartIcon} from '../assets/heart.png'
export {default as FaverateIcon} from '../assets/faverate.png'
export {default as VerifyIcon} from '../assets/verify-icon.svg'
export {default as ThreeDots} from '../assets/threedots.png'
export {default as Post1} from '../assets/post1.png'
export {default as Post2} from '../assets/post2.png'