export {default as Home} from '../assets/home.png'
export {default as Ads} from '../assets/ads.png'
export {default as Chat} from '../assets/chat.png'
export {default as Group} from '../assets/group.png'
export {default as Marketplace} from '../assets/marketplace.png'
export {default as Page} from '../assets/page.png'
export {default as Post} from '../assets/post.png'
export {default as Profile} from '../assets/profile.png'
export {default as Setting} from '../assets/setting.png'

export {default as Online1} from '../assets/online1.png'
export {default as Online2} from '../assets/online2.png'
export {default as Online3} from '../assets/online3.png'
export {default as Online4} from '../assets/online4.png'
export {default as Online5} from '../assets/online5.png'
export {default as Online6} from '../assets/online6.png'
export {default as Online7} from '../assets/online7.png'

export {default as LoginPhone} from '../assets/loginphone.png'
export {default as Login1} from '../assets/login1.png'
export {default as Login2} from '../assets/login2.png'
export {default as Login3} from '../assets/login3.png'
export {default as Logo} from '../assets/logo.png'

